name: bottom_navigation_poc
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.19.0

dependencies:
  auto_route: 8.1.2
  flutter:
    sdk: flutter
  very_good_analysis: ^5.1.0

dev_dependencies:
  auto_route_generator: 8.0.0
  build_runner: 2.3.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
